manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # ▼ 必須: トラックボールを動かすためのドライバー
    - name: zmk-driver-paw3222
      remote: sekigon-gonnoc
      revision: main
    # ▼ 必須: スクロール機能を実現するためのモジュール
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
  self:
    path: config
